import { useState } from "react";
import { json, type LoaderFunctionArgs } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import {
  Page,
  Layout,
  Card,
  Text,
  Badge,
  Button,
  InlineStack,
  BlockStack,
  Banner,
  IndexTable,
  Divider,
  Box,
} from "@shopify/polaris";
import { authenticate } from "../shopify.server";
import { SitemapService } from "../services/sitemap";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  try {
    const { session } = await authenticate.admin(request);
    const shopDomain = session.shop;

    const sitemaps = SitemapService.getSitemapEndpoints(shopDomain);
    const robotsTxtSnippet = SitemapService.generateRobotsTxtLiquid(shopDomain);

    return json({
      shopDomain,
      sitemaps,
      robotsTxtSnippet,
      error: null,
    });
  } catch (error: any) {
    console.error("[Sitemap Loader Error]", error);
    return json({
      shopDomain: "",
      sitemaps: [],
      robotsTxtSnippet: "",
      error: error.message || "Failed to load sitemap details",
    });
  }
};

export default function SitemapRoute() {
  const { shopDomain, sitemaps, robotsTxtSnippet, error } = useLoaderData<typeof loader>();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsTxtSnippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <Page
      title="Shopify Native Sitemap & Robots.txt Studio"
      subtitle="Audit store XML sitemaps, maximize crawl budget efficiency, and configure theme robots.txt.liquid"
      primaryAction={{
        content: copied ? "✓ Robots.txt Copied!" : "Copy Robots.txt Snippet",
        onAction: handleCopy,
      }}
    >
      <BlockStack gap="500">
        {error && (
          <Banner title="Notice" tone="warning">
            <p>{error}</p>
          </Banner>
        )}

        <Banner title="Shopify Native Sitemap Infrastructure" tone="info">
          <p>
            Shopify automatically generates and updates your XML sitemaps whenever products, collections, pages, or blogs are published. Submit your root <code>/sitemap.xml</code> URL in Google Search Console once, and Googlebot will automatically crawl all sub-sitemaps.
          </p>
        </Banner>

        <Layout>
          {/* Sitemaps List */}
          <Layout.Section>
            <Card>
              <BlockStack gap="400">
                <InlineStack align="space-between">
                  <div>
                    <Text as="h2" variant="headingMd">
                      Shopify XML Sitemap Endpoints
                    </Text>
                    <Text as="p" tone="subdued">
                      Direct XML endpoints continuously regenerated by Shopify's core infrastructure.
                    </Text>
                  </div>
                  <Badge tone="success">AUTOMATICALLY UPDATING</Badge>
                </InlineStack>

                <IndexTable
                  resourceName={{ singular: "sitemap", plural: "sitemaps" }}
                  itemCount={sitemaps.length}
                  headings={[
                    { title: "Sitemap Name" },
                    { title: "Description" },
                    { title: "URL Path" },
                    { title: "Status" },
                  ]}
                  selectable={false}
                >
                  {sitemaps.map((s, index) => (
                    <IndexTable.Row id={s.name} key={s.name} position={index}>
                      <IndexTable.Cell>
                        <Text as="span" fontWeight="bold">
                          {s.name}
                        </Text>
                      </IndexTable.Cell>
                      <IndexTable.Cell>
                        <Text as="span" variant="bodyXs" tone="subdued">
                          {s.description}
                        </Text>
                      </IndexTable.Cell>
                      <IndexTable.Cell>
                        <Button
                          variant="plain"
                          url={s.path}
                          target="_blank"
                        >
                          {s.path.replace(`https://${shopDomain}`, "")} ↗
                        </Button>
                      </IndexTable.Cell>
                      <IndexTable.Cell>
                        <Badge tone="success">HEALTHY</Badge>
                      </IndexTable.Cell>
                    </IndexTable.Row>
                  ))}
                </IndexTable>
              </BlockStack>
            </Card>

            <Box paddingBlockStart="400">
              <Card>
                <BlockStack gap="300">
                  <InlineStack align="space-between">
                    <div>
                      <Text as="h2" variant="headingMd">
                        Optimized robots.txt.liquid Snippet
                      </Text>
                      <Text as="p" tone="subdued">
                        Prevents search engines from wasting crawl budget on checkout, cart, and duplicate sort-by URLs while inviting modern AI crawlers.
                      </Text>
                    </div>
                    <Button onClick={handleCopy} size="slim">
                      {copied ? "✓ Copied" : "Copy Code"}
                    </Button>
                  </InlineStack>

                  <Box padding="300" background="bg-surface-secondary" borderRadius="200">
                    <pre
                      style={{
                        margin: 0,
                        fontFamily: "monospace",
                        fontSize: "12px",
                        whiteSpace: "pre-wrap",
                        maxHeight: "260px",
                        overflowY: "auto",
                      }}
                    >
                      {robotsTxtSnippet}
                    </pre>
                  </Box>
                </BlockStack>
              </Card>
            </Box>
          </Layout.Section>

          {/* Installation Instructions */}
          <Layout.Section variant="oneThird">
            <BlockStack gap="400">
              <Card>
                <BlockStack gap="300">
                  <Text as="h2" variant="headingSm">
                    Theme Setup (2 Mins)
                  </Text>
                  <Text as="p" variant="bodyXs" tone="subdued">
                    1. Go to <strong>Online Store &rarr; Themes &rarr; Actions &rarr; Edit code</strong>.
                  </Text>
                  <Text as="p" variant="bodyXs" tone="subdued">
                    2. In the <strong>Templates</strong> folder, click <strong>Add a new template</strong>.
                  </Text>
                  <Text as="p" variant="bodyXs" tone="subdued">
                    3. Select <strong>robots.txt</strong> from the dropdown.
                  </Text>
                  <Text as="p" variant="bodyXs" tone="subdued">
                    4. Paste the snippet on the left and click <strong>Save</strong>.
                  </Text>
                  <Divider />
                  <Text as="p" variant="bodyXs" fontWeight="bold" tone="success">
                    ✓ Preserves 100% of crawl budget for product rankings.
                  </Text>
                </BlockStack>
              </Card>

              <Card>
                <BlockStack gap="200">
                  <Text as="h3" variant="headingSm">
                    🤖 AI Search Whitelist
                  </Text>
                  <Text as="p" variant="bodyXs" tone="subdued">
                    This directive explicitly welcomes:
                  </Text>
                  <Text as="p" variant="bodyXs">
                    • <strong>ChatGPT-User</strong> (OpenAI Search)
                  </Text>
                  <Text as="p" variant="bodyXs">
                    • <strong>PerplexityBot</strong> (Perplexity AI)
                  </Text>
                  <Text as="p" variant="bodyXs">
                    • <strong>ClaudeBot</strong> (Anthropic)
                  </Text>
                  <Text as="p" variant="bodyXs" tone="subdued">
                    Ensuring your store is cited in modern AI answer engines.
                  </Text>
                </BlockStack>
              </Card>
            </BlockStack>
          </Layout.Section>
        </Layout>
      </BlockStack>
    </Page>
  );
}
