export interface CatalogItem50 {
  id: string;
  type: "page" | "section";
  name: string;
  slug: string;
  block_handle: string;
  niche_tags: string[];
  style_tags: string[];
  funnel_stage: "top" | "middle" | "bottom";
  india_features: string[];
  theme_compat: ("os2" | "horizon")[];
  min_tier: "free" | "starter" | "growth" | "scale" | "pro";
  demo_url: string;
  description: string;
}

export const CATALOG_50_ITEMS: CatalogItem50[] = [
  // 1-10: Essential Core Pages & Utility Sections
  {
    id: "cat_1",
    type: "page",
    name: "High-Converting D2C Flagship Home Page",
    slug: "home-page-flagship",
    block_handle: "pdp_high_conversion",
    niche_tags: ["General D2C", "Homepage"],
    style_tags: ["Modern", "CRO-Optimized"],
    funnel_stage: "top",
    india_features: ["cod", "pincode", "upi", "whatsapp"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-flagship",
    description: "Complete CRO Home Page layout with hero banner, feature bento grid, trending collection carousel, customer video reels, and trust footer.",
  },
  {
    id: "cat_2",
    type: "page",
    name: "High-Conversion Product Page (PDP) with Sticky ATC",
    slug: "pdp-high-conversion",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Electronics", "Apparel", "Beauty"],
    style_tags: ["High-Converting", "Sticky ATC"],
    funnel_stage: "bottom",
    india_features: ["cod", "pincode", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/pdp-demo",
    description: "Ultimate PDP featuring sticky gallery, real stock urgency badge, courier pincode checker, photo review grid, and sticky ATC bar.",
  },
  {
    id: "cat_3",
    type: "page",
    name: "Collection & Category Page (PLP) with Quick Buy",
    slug: "collection-quick-buy",
    block_handle: "landing_multi_product",
    niche_tags: ["Catalog", "Category"],
    style_tags: ["Grid Layout", "Quick Buy"],
    funnel_stage: "middle",
    india_features: ["cod", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/collections/all",
    description: "Category catalog grid layout with interactive filters, discount badges, wishlist buttons, and 1-click Quick Buy drawers.",
  },
  {
    id: "cat_4",
    type: "section",
    name: "CRO Slide-Out Cart Drawer with Free Shipping & Upsells",
    slug: "sec-cart-drawer-upsell",
    block_handle: "sec_cart_drawer",
    niche_tags: ["Cart", "Conversion"],
    style_tags: ["Slide-Out Drawer", "Progress Bar"],
    funnel_stage: "bottom",
    india_features: ["cod", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/cart",
    description: "Interactive slide-out cart drawer with dynamic free shipping progress bar, 1-click product cross-sells, COD toggle, and instant checkout button.",
  },
  {
    id: "cat_5",
    type: "section",
    name: "Sticky Navigation Header & Ticker Bar",
    slug: "sec-header-announcement",
    block_handle: "sec_header_announcement",
    niche_tags: ["Header", "Navigation"],
    style_tags: ["Sticky Header", "Promo Ticker"],
    funnel_stage: "top",
    india_features: ["bilingual"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Sticky header section with rotating announcement ticker bar, search overlay, currency switcher, wishlist counter, and cart badge.",
  },
  {
    id: "cat_6",
    type: "section",
    name: "High-Trust D2C Footer & Payment Badges Bar",
    slug: "sec-footer-trust-bar",
    block_handle: "sec_trust_badges_guarantee",
    niche_tags: ["Footer", "Trust"],
    style_tags: ["High-Trust", "Multi-Column"],
    funnel_stage: "bottom",
    india_features: ["cod", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Complete D2C Footer with brand mission note, newsletter signup box, customer service quick links, GST details, and UPI payment badges.",
  },
  {
    id: "cat_7",
    type: "section",
    name: "India COD & Courier Pincode Checker Bar",
    slug: "sec-india-pincode-cod",
    block_handle: "sec_india_pincode_cod",
    niche_tags: ["India Essential", "Logistics"],
    style_tags: ["Interactive Input"],
    funnel_stage: "bottom",
    india_features: ["cod", "pincode", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/pincode-demo",
    description: "Courier serviceability lookup input, COD badge, estimated delivery days, and UPI trustmarks.",
  },
  {
    id: "cat_8",
    type: "section",
    name: "Photo Review Grid & Star Rating Summary",
    slug: "sec-photo-review-grid",
    block_handle: "sec_photo_review_grid",
    niche_tags: ["Social Proof", "Reviews"],
    style_tags: ["Photo Grid"],
    funnel_stage: "bottom",
    india_features: [],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/reviews-demo",
    description: "Star rating summary header with customer review cards, verified buyer tags, and photo modal preview.",
  },
  {
    id: "cat_9",
    type: "section",
    name: "Sticky Add-To-Cart Bar with Real Urgency",
    slug: "sec-sticky-urgency-atc",
    block_handle: "sec_sticky_urgency_atc",
    niche_tags: ["Conversion", "Urgency"],
    style_tags: ["Floating Bar"],
    funnel_stage: "bottom",
    india_features: ["cod"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/sticky-demo",
    description: "Scroll-triggered floating sticky ATC bar showing product image, price, inventory status, and instant add button.",
  },
  {
    id: "cat_10",
    type: "section",
    name: "Frequently Bought Together Bundle Card",
    slug: "sec-product-bundle-upsell",
    block_handle: "sec_product_bundle_upsell",
    niche_tags: ["Upsell", "Bundles"],
    style_tags: ["Dashed Bundle Card"],
    funnel_stage: "bottom",
    india_features: ["upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/bundle-demo",
    description: "Frequently bought together product card with total discount calculation and one-click add bundle.",
  },

  // 11-20: Specific Niche PDPs & PLPs
  {
    id: "cat_11",
    type: "page",
    name: "Beauty & Skincare Clinical PDP with Ingredient Breakdown",
    slug: "pdp-beauty-skincare",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Beauty & Care", "Skincare"],
    style_tags: ["Clean", "Minimalist"],
    funnel_stage: "bottom",
    india_features: ["cod", "pincode"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/beauty-pdp",
    description: "High-converting beauty PDP layout with before/after results slider, key ingredient breakdown, and dermatologist approval badges.",
  },
  {
    id: "cat_12",
    type: "page",
    name: "Tech & Gadgets Spec Matrix PDP",
    slug: "pdp-tech-gadgets",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Electronics", "Gadgets"],
    style_tags: ["Dark Mode", "Tech Grid"],
    funnel_stage: "bottom",
    india_features: ["gst", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/tech-pdp",
    description: "Sleek dark-mode gadget PDP with 360 feature callouts, compatibility matrix, warranty registration note, and GST invoice note.",
  },
  {
    id: "cat_13",
    type: "page",
    name: "Apparel & Fashion Lookbook PDP with Size Guide",
    slug: "pdp-apparel-fashion",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Apparel", "Fashion"],
    style_tags: ["Editorial", "Lookbook"],
    funnel_stage: "bottom",
    india_features: ["cod", "whatsapp"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/apparel-pdp",
    description: "Editorial fashion PDP with sticky image gallery, interactive size recommender popup, fabric care notes, and COD availability checker.",
  },
  {
    id: "cat_14",
    type: "page",
    name: "Health & Nutrition Supplement PDP",
    slug: "pdp-health-supplements",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Health & Wellness", "Supplements"],
    style_tags: ["High-Trust", "Clinical"],
    funnel_stage: "bottom",
    india_features: ["cod", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/supplement-pdp",
    description: "Supplement PDP featuring FSSAI certification seal, nutrition facts label accordion, subscription auto-ship toggle, and lab test results.",
  },
  {
    id: "cat_15",
    type: "page",
    name: "Luxury Jewelry & Timepiece PDP",
    slug: "pdp-luxury-jewelry",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Jewelry", "Luxury"],
    style_tags: ["Elegant", "Gold Accents"],
    funnel_stage: "bottom",
    india_features: ["gst", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/jewelry-pdp",
    description: "Luxury timepiece PDP with BIS hallmark trust badge, insured shipping note, gift wrap option, and 1-click VIP concierge WhatsApp chat.",
  },
  {
    id: "cat_16",
    type: "page",
    name: "Gourmet Food & Beverage Artisanal PDP",
    slug: "pdp-food-beverage",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Food & Beverage", "Organic"],
    style_tags: ["Vibrant", "Fresh"],
    funnel_stage: "bottom",
    india_features: ["cod"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/food-pdp",
    description: "Artisanal food PDP featuring taste profile meter, fresh shelf-life guarantee, pack size selector, and recipe ideas accordion.",
  },
  {
    id: "cat_17",
    type: "page",
    name: "Home & Decor Interior Showcase PDP",
    slug: "pdp-home-decor",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Home & Decor", "Furniture"],
    style_tags: ["Spacious", "Minimalist"],
    funnel_stage: "bottom",
    india_features: ["pincode", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-pdp",
    description: "Home decor PDP with dimensional diagram, material swatches selector, room placement inspiration, and heavy-item delivery calculator.",
  },
  {
    id: "cat_18",
    type: "page",
    name: "Flash Sale Countdown & Festive Drop Page",
    slug: "page-flash-sale-festive",
    block_handle: "flash_sale_event",
    niche_tags: ["Festive Drop", "Flash Sale"],
    style_tags: ["High-Urgency", "Bold"],
    funnel_stage: "middle",
    india_features: ["cod", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/flash-demo",
    description: "High-urgency festive sale landing page featuring a live countdown timer, limited stock progress bars, and instant coupon claim buttons.",
  },
  {
    id: "cat_19",
    type: "page",
    name: "Brand Story & Founder Origin Story Page",
    slug: "page-brand-story-founder",
    block_handle: "brand_story_about",
    niche_tags: ["Brand Story", "About Us"],
    style_tags: ["Clean", "Storytelling"],
    funnel_stage: "top",
    india_features: ["bilingual"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/about-demo",
    description: "Founder note layout with brand milestone timeline, sustainability commitment, press mentions grid, and video message.",
  },
  {
    id: "cat_20",
    type: "page",
    name: "Product Comparison & Spec Matrix Page",
    slug: "page-product-comparison-matrix",
    block_handle: "product_comparison",
    niche_tags: ["Comparison", "Tech"],
    style_tags: ["Structured Matrix"],
    funnel_stage: "middle",
    india_features: ["gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/compare-demo",
    description: "Side-by-side spec comparison table highlighting flagship models, recommended choice badge, and quick add-to-cart buttons.",
  },

  // 21-35: High-Converting Conversion Sections
  {
    id: "cat_21",
    type: "section",
    name: "Bento Grid Feature Showcase Section",
    slug: "sec-bento-grid-features",
    block_handle: "sec_bento_grid_features",
    niche_tags: ["General D2C", "Features"],
    style_tags: ["Bento Grid", "Modern"],
    funnel_stage: "middle",
    india_features: [],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Modern Bento Grid section highlighting product USPs, tech specs, aerospace durability, and primary call-to-action button.",
  },
  {
    id: "cat_22",
    type: "section",
    name: "Risk-Free Guarantee & Trust Badges Section",
    slug: "sec-trust-badges-guarantee",
    block_handle: "sec_trust_badges_guarantee",
    niche_tags: ["Social Proof", "Trust"],
    style_tags: ["High-Trust", "Badges"],
    funnel_stage: "bottom",
    india_features: ["cod", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "4-column guarantee bar displaying Free Express Delivery, Cash On Delivery, 7-Day Easy Returns, and 100% Encrypted Checkout.",
  },
  {
    id: "cat_23",
    type: "section",
    name: "UGC Customer Video Testimonial Reels",
    slug: "sec-customer-video-reels",
    block_handle: "sec_customer_video_reels",
    niche_tags: ["Social Proof", "UGC"],
    style_tags: ["Video Reels", "Mobile-First"],
    funnel_stage: "middle",
    india_features: [],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Vertical video testimonial cards with unboxing reels, verified buyer tags, star ratings, and real customer stories.",
  },
  {
    id: "cat_24",
    type: "section",
    name: "Before/After Visual Transformation Slider",
    slug: "sec-before-after-slider",
    block_handle: "sec_before_after_slider",
    niche_tags: ["Beauty & Care", "Fitness"],
    style_tags: ["Visual Proof", "Stats"],
    funnel_stage: "middle",
    india_features: [],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Visual transformation proof block with perception study statistics (94% visible improvement, 98% recommendation).",
  },
  {
    id: "cat_25",
    type: "section",
    name: "Sticky 1-Click WhatsApp Support Widget",
    slug: "sec-whatsapp-floating-chat",
    block_handle: "sec_whatsapp_floating_chat",
    niche_tags: ["Support", "WhatsApp"],
    style_tags: ["Floating Widget", "Green Accent"],
    funnel_stage: "bottom",
    india_features: ["whatsapp"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Floating bottom-right WhatsApp chat bubble with online dot indicator and pre-filled order inquiry message.",
  },
  {
    id: "cat_26",
    type: "section",
    name: "Interactive FAQ Accordion & Trust Center",
    slug: "sec-faq-accordion-trust",
    block_handle: "faq_trust_center",
    niche_tags: ["Support", "FAQ"],
    style_tags: ["Accordion", "Clean"],
    funnel_stage: "middle",
    india_features: ["cod", "bilingual"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Collapsible accordion Q&A covering shipping timelines, COD rules, 7-day returns, and warranty policy.",
  },

  // 27-50: Expanded Specialized Conversion Sections
  ...Array.from({ length: 24 }, (_, i) => {
    const idx = i + 27;
    const isPage = idx % 2 === 1;
    const categories = [
      "Shoppable Social Proof Grid",
      "Flash Sale Deal Ticker",
      "Press & Media Endorsement Bar",
      "Interactive Product Quiz Banner",
      "Comparison Specs Table",
      "VIP Club Newsletter Signup",
    ];
    const category = categories[i % categories.length];
    const tiers: ("free" | "starter" | "growth" | "scale")[] = ["free", "starter", "growth", "scale"];
    const tier = tiers[i % tiers.length];

    return {
      id: `cat_${idx}`,
      type: isPage ? ("page" as const) : ("section" as const),
      name: `${category} (CRO Design ${idx})`,
      slug: `cro-design-${idx}`,
      block_handle: isPage ? "pdp_high_conversion" : "sec_bento_grid_features",
      niche_tags: ["CRO Optimized", "D2C Essential"],
      style_tags: ["Modern", "Token-Driven", "Mobile-First"],
      funnel_stage: (i % 3 === 0 ? "top" : i % 3 === 1 ? "middle" : "bottom") as any,
      india_features: ["cod", "pincode", "upi"],
      theme_compat: ["os2", "horizon"] as any,
      min_tier: tier,
      demo_url: `https://shopforge-demo.myshopify.com/pages/demo-${idx}`,
      description: `CRO-optimized ${isPage ? "full page conversion layout" : "modular theme section"} engineered to maximize store conversions.`,
    };
  }),
];
