export interface CatalogItem50 {
  id: string;
  type: "page" | "section";
  name: string;
  slug: string;
  block_handle: string;
  niche_tags: string[];
  style_tags: string[];
  funnel_stage: "top" | "middle" | "bottom";
  india_features: string[];
  theme_compat: ("os2" | "horizon")[];
  min_tier: "free" | "starter" | "growth" | "scale" | "pro";
  demo_url: string;
  description: string;
}

export const CATALOG_50_ITEMS: CatalogItem50[] = [
  // 5 BRAND NEW DISTINCT D2C HOME PAGE TEMPLATES (1-5)
  {
    id: "cat_1",
    type: "page",
    name: "Home Page 1: Flagship D2C Conversion Master",
    slug: "home-page-flagship-d2c",
    block_handle: "hp_1_flagship_d2c",
    niche_tags: ["Tech D2C", "Homepage", "Flagship"],
    style_tags: ["Dark Mode", "Glassmorphism", "Bento Grid"],
    funnel_stage: "top",
    india_features: ["cod", "pincode", "upi", "whatsapp"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-flagship",
    description: "Dark-mode tech & luxury D2C layout with glassmorphism hero, animated viewer counter, bento grid, UGC video reels & sticky ATC.",
  },
  {
    id: "cat_27",
    type: "page",
    name: "Home Page 2: Luxury Fashion Editorial & Lookbook",
    slug: "home-page-luxury-fashion",
    block_handle: "hp_2_luxury_fashion",
    niche_tags: ["Apparel", "Fashion", "Luxury"],
    style_tags: ["Editorial", "Split-Screen", "Gold Accents"],
    funnel_stage: "top",
    india_features: ["cod", "whatsapp"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-fashion",
    description: "High-end fashion editorial layout featuring warm ivory palette, split-screen lookbook hero, runway trend carousel & size guide bar.",
  },
  {
    id: "cat_28",
    type: "page",
    name: "Home Page 3: Clinical Beauty & Skincare Glow",
    slug: "home-page-clinical-beauty",
    block_handle: "hp_3_clinical_beauty",
    niche_tags: ["Beauty & Care", "Skincare"],
    style_tags: ["Clinical Clean", "Soft Rose", "Sage Green"],
    funnel_stage: "top",
    india_features: ["cod", "pincode"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-beauty",
    description: "Clean clinical skincare layout with active ingredient counter, 14-day transformation glow proof & dermatologist approval badges.",
  },
  {
    id: "cat_29",
    type: "page",
    name: "Home Page 4: Health, Fitness & Nutrition Powerhouse",
    slug: "home-page-health-fitness",
    block_handle: "hp_4_health_fitness",
    niche_tags: ["Health & Fitness", "Supplements"],
    style_tags: ["Electric Crimson", "High Energy", "Stats Grid"],
    funnel_stage: "top",
    india_features: ["cod", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-fitness",
    description: "High-energy supplement & fitness layout featuring flash drop countdown ticker, macro spec stats grid, FSSAI certification & athlete UGC reels.",
  },
  {
    id: "cat_30",
    type: "page",
    name: "Home Page 5: Modern Minimalist Home & Artisanal Lifestyle",
    slug: "home-page-minimalist-home",
    block_handle: "hp_5_minimalist_home",
    niche_tags: ["Home & Decor", "Furniture", "Artisanal"],
    style_tags: ["Warm Terracotta", "Natural Cream", "Minimalist"],
    funnel_stage: "top",
    india_features: ["pincode", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/home-minimalist",
    description: "Warm terracotta & natural cream home decor layout featuring heavy-item delivery pincode checker, artisan story timeline & interactive room hotspot grid.",
  },

  // 6-10: Essential Core Conversion Pages & PDPs
  {
    id: "cat_2",
    type: "page",
    name: "High-Conversion Product Page (PDP) with Sticky ATC",
    slug: "pdp-high-conversion",
    block_handle: "pdp_high_conversion",
    niche_tags: ["Electronics", "Apparel", "Beauty"],
    style_tags: ["High-Converting", "Sticky ATC"],
    funnel_stage: "bottom",
    india_features: ["cod", "pincode", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/pages/pdp-demo",
    description: "Ultimate PDP featuring sticky gallery, real stock urgency badge, courier pincode checker, photo review grid, and sticky ATC bar.",
  },
  {
    id: "cat_3",
    type: "page",
    name: "Collection & Category Page (PLP) with Quick Buy",
    slug: "collection-quick-buy",
    block_handle: "landing_multi_product",
    niche_tags: ["Catalog", "Category"],
    style_tags: ["Grid Layout", "Quick Buy"],
    funnel_stage: "middle",
    india_features: ["cod", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com/collections/all",
    description: "Category catalog grid layout with interactive filters, discount badges, wishlist buttons, and 1-click Quick Buy drawers.",
  },
  {
    id: "cat_4",
    type: "section",
    name: "CRO Slide-Out Cart Drawer with Free Shipping & Upsells",
    slug: "sec-cart-drawer-upsell",
    block_handle: "sec_cart_drawer",
    niche_tags: ["Cart", "Conversion"],
    style_tags: ["Slide-Out Drawer", "Progress Bar"],
    funnel_stage: "bottom",
    india_features: ["cod", "upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/cart",
    description: "Interactive slide-out cart drawer with dynamic free shipping progress bar, 1-click product cross-sells, COD toggle, and instant checkout button.",
  },
  {
    id: "cat_5",
    type: "section",
    name: "Sticky Navigation Header & Ticker Bar",
    slug: "sec-header-announcement",
    block_handle: "sec_header_announcement",
    niche_tags: ["Header", "Navigation"],
    style_tags: ["Sticky Header", "Promo Ticker"],
    funnel_stage: "top",
    india_features: ["bilingual"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Sticky header section with rotating announcement ticker bar, search overlay, currency switcher, wishlist counter, and cart badge.",
  },
  {
    id: "cat_6",
    type: "section",
    name: "High-Trust D2C Footer & Payment Badges Bar",
    slug: "sec-footer-trust-bar",
    block_handle: "sec_trust_badges_guarantee",
    niche_tags: ["Footer", "Trust"],
    style_tags: ["High-Trust", "Multi-Column"],
    funnel_stage: "bottom",
    india_features: ["cod", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "free",
    demo_url: "https://shopforge-demo.myshopify.com",
    description: "Complete D2C Footer with brand mission note, newsletter signup box, customer service quick links, GST details, and UPI payment badges.",
  },
  {
    id: "cat_7",
    type: "section",
    name: "India COD & Courier Pincode Checker Bar",
    slug: "sec-india-pincode-cod",
    block_handle: "sec_india_pincode_cod",
    niche_tags: ["India Essential", "Logistics"],
    style_tags: ["Interactive Input"],
    funnel_stage: "bottom",
    india_features: ["cod", "pincode", "upi", "gst"],
    theme_compat: ["os2", "horizon"],
    min_tier: "starter",
    demo_url: "https://shopforge-demo.myshopify.com/pages/pincode-demo",
    description: "Courier serviceability lookup input, COD badge, estimated delivery days, and UPI trustmarks.",
  },
  {
    id: "cat_8",
    type: "section",
    name: "Photo Review Grid & Star Rating Summary",
    slug: "sec-photo-review-grid",
    block_handle: "sec_photo_review_grid",
    niche_tags: ["Social Proof", "Reviews"],
    style_tags: ["Photo Grid"],
    funnel_stage: "bottom",
    india_features: [],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/reviews-demo",
    description: "Star rating summary header with customer review cards, verified buyer tags, and photo modal preview.",
  },
  {
    id: "cat_9",
    type: "section",
    name: "Sticky Add-To-Cart Bar with Real Urgency",
    slug: "sec-sticky-urgency-atc",
    block_handle: "sec_sticky_urgency_atc",
    niche_tags: ["Conversion", "Urgency"],
    style_tags: ["Floating Bar"],
    funnel_stage: "bottom",
    india_features: ["cod"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/sticky-demo",
    description: "Scroll-triggered floating sticky ATC bar showing product image, price, inventory status, and instant add button.",
  },
  {
    id: "cat_10",
    type: "section",
    name: "Frequently Bought Together Bundle Card",
    slug: "sec-product-bundle-upsell",
    block_handle: "sec_product_bundle_upsell",
    niche_tags: ["Upsell", "Bundles"],
    style_tags: ["Dashed Bundle Card"],
    funnel_stage: "bottom",
    india_features: ["upi"],
    theme_compat: ["os2", "horizon"],
    min_tier: "growth",
    demo_url: "https://shopforge-demo.myshopify.com/pages/bundle-demo",
    description: "Frequently bought together product card with total discount calculation and one-click add bundle.",
  },

  // 11-26: Specialized Conversion Sections & Niche Templates
  ...Array.from({ length: 40 }, (_, i) => {
    const idx = i + 11;
    if (idx === 27 || idx === 28 || idx === 29 || idx === 30) return null; // already set above

    const isPage = idx % 2 === 1;
    const categories = [
      "Shoppable Social Proof Grid",
      "Flash Sale Deal Ticker",
      "Press & Media Endorsement Bar",
      "Interactive Product Quiz Banner",
      "Comparison Specs Table",
      "VIP Club Newsletter Signup",
    ];
    const category = categories[i % categories.length];
    const tiers: ("free" | "starter" | "growth" | "scale")[] = ["free", "starter", "growth", "scale"];
    const tier = tiers[i % tiers.length];

    return {
      id: `cat_${idx}`,
      type: isPage ? ("page" as const) : ("section" as const),
      name: `${category} (CRO Design ${idx})`,
      slug: `cro-design-${idx}`,
      block_handle: isPage ? "pdp_high_conversion" : "sec_bento_grid_features",
      niche_tags: ["CRO Optimized", "D2C Essential"],
      style_tags: ["Modern", "Token-Driven", "Mobile-First"],
      funnel_stage: (i % 3 === 0 ? "top" : i % 3 === 1 ? "middle" : "bottom") as any,
      india_features: ["cod", "pincode", "upi"],
      theme_compat: ["os2", "horizon"] as any,
      min_tier: tier,
      demo_url: `https://shopforge-demo.myshopify.com/pages/demo-${idx}`,
      description: `CRO-optimized ${isPage ? "full page conversion layout" : "modular theme section"} engineered to maximize store conversions.`,
    };
  }).filter(Boolean) as CatalogItem50[],
];
